[package]
name = "dominant_colours"
version = "1.1.2"
edition = "2018"

[dependencies]
assert_cmd = "2.0.2"
clap = "2.33"

[dependencies.kmeans_colors]
version = "0.4.0"
features = ["palette_color"]
default-features = false

[dependencies.image]
version = "0.24"
features = ["jpeg", "png", "gif", "tiff"]
default-features = false

[dependencies.palette]
version = "0.5"
default-features = false
features = ["std"]
